// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCDQsY_8khpyxzvB8a1OooBgU1rwfI1M',
    appId: '1:716153267177:web:7b71feed7405fe6ef2a178',
    messagingSenderId: '716153267177',
    projectId: 'dealsdray',
    authDomain: 'dealsdray.firebaseapp.com',
    storageBucket: 'dealsdray.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzEOHL3dZTXrRcdAd5ESbFdr7XVY2KFKI',
    appId: '1:716153267177:android:6a383eb02f2fdb98f2a178',
    messagingSenderId: '716153267177',
    projectId: 'dealsdray',
    storageBucket: 'dealsdray.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBtgEknSF8kTWrqRxidCtKC1GW49pZbw',
    appId: '1:716153267177:ios:1bfd952ed7c3ad4bf2a178',
    messagingSenderId: '716153267177',
    projectId: 'dealsdray',
    storageBucket: 'dealsdray.appspot.com',
    iosBundleId: 'com.example.dealsdray',
  );

}